// <auto-generated />
namespace Benefits.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedtables3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtables3));
        
        string IMigrationMetadata.Id
        {
            get { return "201812252058486_changedtables3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
